plugins {
    id 'com.android.application'
}

android {
    namespace 'com.deskmint.dashboard'
    compileSdk 35

    defaultConfig {
        applicationId 'com.deskmint.dashboard'
        minSdk 17
        targetSdk 28
        versionCode 3
        versionName '2.1-a3000h'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
